const ethers = require("ethers");
const { ABI } = require("./abi.js");
const { ADDRESS, ADDRESS_AUCTION } = require("./address.js");
const { PROVIDERS, MAINNETSIGNER, SIGNER } = require("./providers.js");
const { CONFIG } = require("./config.js");

const CONTRACTS = {
  WINBOOSTERSIGNER: {
    [CONFIG.CHAINNAME]: new ethers.Contract(
      ADDRESS[CONFIG.CHAINNAME].WINBOOSTER,
      ABI.WINBOOSTER,
      SIGNER
    ),
  },
  WINBOOSTER: {
    [CONFIG.CHAINNAME]: new ethers.Contract(
      ADDRESS[CONFIG.CHAINNAME].WINBOOSTER,
      ABI.WINBOOSTER,
      PROVIDERS[CONFIG.CHAINNAME]
    ),
  },
  WINBOOSTSIGNER: {
    [CONFIG.CHAINNAME]: new ethers.Contract(
      ADDRESS[CONFIG.CHAINNAME].WINBOOST,
      ABI.WINBOOST,
      SIGNER
    ),
  },
  WINBOOST: {
    [CONFIG.CHAINNAME]: new ethers.Contract(
      ADDRESS[CONFIG.CHAINNAME].WINBOOST,
      ABI.WINBOOST,
      PROVIDERS[CONFIG.CHAINNAME]
    ),
  },
  // mainnet

  LINKSIGNER: new ethers.Contract(
    ADDRESS_AUCTION.MAINNET.LINK,
    ABI.LINK,
    MAINNETSIGNER
  ),
  SWAPPERSIGNER: {
    [CONFIG.CHAINNAME]: new ethers.Contract(
      ADDRESS[CONFIG.CHAINNAME].SWAPPER,
      ABI.SWAPPER,
      SIGNER
    ),
  },

  PRIZESANTASIGNER: {
    [CONFIG.CHAINNAME]: new ethers.Contract(
      ADDRESS[CONFIG.CHAINNAME].PRIZESANTA,
      ABI.PRIZESANTA,
      SIGNER
    ),
  },
  /*  GAS: {
  [CONFIG.CHAINNAME]: new ethers.Contract(
   ADDRESS[CONFIG.CHAINNAME].GAS,
   ABI.OPGAS,
   PROVIDERS[CONFIG.CHAINNAME]
   ),
},*/
  CLAIMER: {
    [CONFIG.CHAINNAME]: new ethers.Contract(
      ADDRESS[CONFIG.CHAINNAME].CLAIMER,
      ABI.CLAIMER,
      PROVIDERS[CONFIG.CHAINNAME]
    ),
  },
  VAULTS: {
    [CONFIG.CHAINNAME]: ADDRESS[CONFIG.CHAINNAME].VAULTS.map((vault) => ({
      LIQUIDATIONPAIR: new ethers.Contract(
        vault.LIQUIDATIONPAIR,
        ABI.LIQUIDATIONPAIR,
        PROVIDERS[CONFIG.CHAINNAME]
      ),
      VAULT: new ethers.Contract(
        vault.VAULT,
        ABI.VAULT,
        PROVIDERS[CONFIG.CHAINNAME]
      ),
    })),
  },
  LIQUIDATIONROUTER: {
    [CONFIG.CHAINNAME]: new ethers.Contract(
      ADDRESS[CONFIG.CHAINNAME].LIQUIDATIONROUTER,
      ABI.LIQUIDATIONROUTER,
      PROVIDERS[CONFIG.CHAINNAME]
    ),
  },
  LIQUIDATIONPAIRFACTORY: {
    [CONFIG.CHAINNAME]: new ethers.Contract(
      ADDRESS[CONFIG.CHAINNAME].LIQUIDATIONPAIRFACTORY,
      ABI.LIQUIDATIONPAIRFACTORY,
      PROVIDERS[CONFIG.CHAINNAME]
    ),
  },
  POOL: {
    [CONFIG.CHAINNAME]: new ethers.Contract(
      ADDRESS[CONFIG.CHAINNAME].PRIZETOKEN.ADDRESS,
      ABI.POOL,
      PROVIDERS[CONFIG.CHAINNAME]
    ),
  },
  TOKENFAUCET: {
    [CONFIG.CHAINNAME]: new ethers.Contract(
      ADDRESS[CONFIG.CHAINNAME].TOKENFAUCET,
      ABI.TOKENFAUCET,
      SIGNER
    ),
  },
  PRIZEPOOL: {
    [CONFIG.CHAINNAME]: new ethers.Contract(
      ADDRESS[CONFIG.CHAINNAME].PRIZEPOOL,
      ABI.PRIZEPOOL,
      PROVIDERS[CONFIG.CHAINNAME]
    ),
  },
  RNGRELAYAUCTION: {
    [CONFIG.CHAINNAME]: new ethers.Contract(
      ADDRESS[CONFIG.CHAINNAME].RNGRELAYAUCTION,
      ABI.RNGRELAYAUCTION,
      PROVIDERS[CONFIG.CHAINNAME]
    ),
  },
  RNGAUCTION: {
    MAINNET: new ethers.Contract(
      ADDRESS_AUCTION.MAINNET.RNGAUCTION,
      ABI.RNGAUCTION,
      PROVIDERS["MAINNET"]
    ),
  },
  CHAINLINKDIRECTAUCTIONHELPER: {
    MAINNET: new ethers.Contract(
      ADDRESS_AUCTION.MAINNET.CHAINLINKDIRECTAUCTIONHELPER,
      ABI.CHAINLINKDIRECTAUCTIONHELPER,
      PROVIDERS["MAINNET"]
    ),
  },
  CHAINLINKDIRECTAUCTIONHELPERWITHSIGNER: {
    MAINNET: new ethers.Contract(
      ADDRESS_AUCTION.MAINNET.CHAINLINKDIRECTAUCTIONHELPER,
      ABI.CHAINLINKDIRECTAUCTIONHELPER,
      MAINNETSIGNER
    ),
  },

  RNGAUCTIONRELAYWITHSIGNER: {
    MAINNET: new ethers.Contract(
      ADDRESS_AUCTION.MAINNET.RNGAUCTIONRELAY,
      ABI.RNGAUCTIONRELAY,
      MAINNETSIGNER
    ),
  },

  PRIZEPOOLWITHSIGNER: {
    [CONFIG.CHAINNAME]: new ethers.Contract(
      ADDRESS[CONFIG.CHAINNAME].PRIZEPOOL,
      ABI.PRIZEPOOL,
      SIGNER
    ),
  },
  POOLWITHSIGNER: {
    [CONFIG.CHAINNAME]: new ethers.Contract(
      ADDRESS[CONFIG.CHAINNAME].PRIZETOKEN.ADDRESS,
      ABI.POOL,
      SIGNER
    ),
  },
  LIQUIDATIONROUTERSIGNER: {
    [CONFIG.CHAINNAME]: new ethers.Contract(
      ADDRESS[CONFIG.CHAINNAME].LIQUIDATIONROUTER,
      ABI.LIQUIDATIONROUTER,
      SIGNER
    ),
  },
};

module.exports = { CONTRACTS };
